# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('flavour_title', models.CharField(max_length=500)),
                ('made_in', models.CharField(max_length=250)),
                ('flavour_image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('name_title', models.CharField(max_length=250)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Flavour')),
            ],
        ),
    ]
