# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='file_type',
            new_name='product_type',
        ),
    ]
