# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171027_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='product_type',
            field=models.CharField(max_length=250),
        ),
    ]
