# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20171027_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
