# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_name_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='is_favorite',
        ),
    ]
